version: '3.8'

# 이 파일로 관리할 서비스 컨테이너들의 목록을 정의함
services:
  # 서비스의 이름을 ai-dev로 지정 (원하는대로 바꿀수 있음)
  ai-dev:
    # 이미지를 빌드하는 방법에 대한 설정
    build:
      # 현재 디렉토리('.')에 있는 Dockerfile을 사용하여 이미지를 빌드
      context: .
    # 빌드된 이미지에 이름을 붙여준다
    image: jp6:jp6
    # 실행될 컨테이너의 이름을 'sadasd'로 지정
    container_name: my-dev-container    
    # 'docker run -it' 와 동일한 효과를 줍니다. (컨테이너와 상호작용)
    stdin_open: true
    tty: true
    # -- 추가/수정된 부분 시작 ---
    environment:
      - TZ=Asia/Seoul
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1  # Qt GUI 안정성 향상
      - XAUTHORITY=/tmp/.docker.xauth  # X11 인증
    # 'docker run -v'와 동일한 효과
    #  Host의 현재 폴더(.)를 컨테이너의 /project 폴더와 연결
    volumes:
      - .:/project
      # X11 소켓 연결 (GUI 표시를 위해 필수!)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # X11 인증 파일 (선택적)
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
   # 디바이스 접근 권한 (카메라 및 GPU 사용시)
    devices:
      - /dev/nvhost-ctrl-gpu:/dev/nvhost-ctrl-gpu  # GPU 제어
      - /dev/nvmap:/dev/nvmap  # NVIDIA 메모리 맵
      - /dev/nvhost-prof-gpu:/dev/nvhost-prof-gpu  # GPU 프로파일링
      - /dev/nvhost-gpu:/dev/nvhost-gpu  # GPU 디바이스
      - /dev/nvhost-as-gpu:/dev/nvhost-as-gpu  # GPU 주소 공간
    # 네트워크 설정 (X11 포워딩 최적화)
    network_mode: host 
    # NVIDIA GPU를 사용하기 위한 필수 설정입니다.
    # (daemon.json에 default로 설정했지만, 명시적으로 적어주는 것이 좋습니다.)
    runtime: nvidia
    ipc: host

    # 컨테이너가 중지되었을 때, 수동으로 재시작하지 않는 이상 다시 시작하지 않도록 설정합니다.
    # 개발 중에는 이 설정이 편리할 수 있습니다.
    restart: 'no'